# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: i can website wheee
email: mckinleyxie+website@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello! This is the personal website of Mckinley Xie.
  #twitter_username: username
github_username: MckinleyX
minimal_mistakes_skin: sunrise
search: false

# Build settings
markdown: kramdown
  #theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
  #paginate: 0 # amount of posts to show
  #paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  #- jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mckinley Xie"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Hey! I'm a high school student interested in math,
    computer science, and Linux."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://MckinleyX.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mckinleyx"
    - label: "Email"
      icon: "fal fa-fw fa-envelope"
      url: "mailto:mckinleyxie+website@protonmail.com"

footer:
  links:
    #    - label: "Twitter"
    #      icon: "fab fa-fw fa-twitter-square"
    #      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mckinleyx"
        #    - label: "Instagram"
        #      icon: "fab fa-fw fa-instagram"
        #      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _math
  - scope:
      path: ""
      type: math
    values:
      layout: single
      author_profile: true
      share: false

        #category_archive:
        #  type: liquid
        #  path: /categories/
        #tag_archive:
        #  type: liquid
        #  path: /tags/
collections:
  math:
    output: true
    permalink: /:collection/:path/
